# fly.toml app configuration file generated for linkbot on 2023-09-11T15:59:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linkbot"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
services = []

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  NODE_ENV="production"

[[services]]
  http_checks = []

[experimental]
  allowed_public_ports = []
  auto_rollback = true