# fly.toml app configuration file generated for linkbot on 2023-09-11T15:59:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linkbot"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true