# fly.toml app configuration file generated for linkbot on 2023-09-11T15:59:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linkbot"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
services = []

[[services]]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  NODE_ENV="production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true